language: python
sudo: false
python:
    - "2.7"
branches:
    only:
        - master
        - /^v[0-9].*$/
addons:
    apt:
        packages:
            - gfortran
before_install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
    - conda config --add channels conda-forge
    - conda update -q conda
    - conda info -a
install:
    # Create conda matching requirements
    - conda create -n test -c conda-forge python=$TRAVIS_PYTHON_VERSION
    - conda env update -n test -f environment.yaml
    - source activate test
    # Rest of dependencies
    - "pip install -r requirements/dev.txt"
    - "pip install pytest"
    # Install YATSM
    - "pip install -e ."
script:
    - py.test -ra tests/
    # Disable numba JIT for coverage to correctly identify JIT-ed lines
    # See: http://stackoverflow.com/questions/26875191/analyzing-coverage-of-numba-wrapped-functions
    - NUMBA_DISABLE_JIT=1 coverage run --source yatsm -m py.test
after_success:
    - pip install coveralls
    - coverage report
    - coveralls
before_cache:
    # Deactivate conda so we use system 'curl'
    - source deactivate
