# http://json-schema.org/example2.html
"$schema": "http://json-schema.org/draft-04/schema#"
description: YATSM configuration
type: object
properties:
    version:
        type: string
    # TODO: pattern:
    data:
        "$ref": "#/definitions/data"
    pipeline:
        "$ref": "#/definitions/pipeline"
required:
    - version

definitions:
    data:
        type: object
        description: "Datasets"
        properties:
            primary:
                type: string
            datasets:
                type: object
                minProperties: 1
                patternProperties:
                    # Datasets can be labeled anything the user wants...
                    ".*":
                        "$ref": "#/definitions/datasets"
            cache_dir:
                type: string
                default: ""
        required:
            - datasets
            - primary
        additionalProperties: False
    datasets:
        type: object
        properties:
            reader:
                properties:
                    name:
                        enum: ["GDAL", "AGDCv2"]
                    config:
                        oneOf:
                            - "$ref": "#/definitions/readers/GDAL"
                            - "$ref": "#/definitions/readers/AGDCv2"
                required:
                    - name
                    - config
            mask_band:
                oneOf:
                    - type: string
                    - type: "null"
                default: ""
            mask_values:
                oneOf:
                    - "$ref": "#/types/array_num"
                    - type: "null"
                default: []
            min_values:
                "$ref": "#/types/array_num"
                default: []
            max_values:
                "$ref": "#/types/array_num"
                default: []
        required:
            - reader
    readers:
        GDAL:
            type: object
            properties:
                input_file:
                    type: string
                date_column:
                    type: string
                date_format:
                    type: string
                band_names:
                    type: array
                    uniqueItems: true
                    items:
                        type: string
                keep_open:
                    type: boolean
                    default: True
                column_dtype:
                    type: object
                    minProperties: 1
                    patternProperties:
                        ".*":
                            type: string
            required:
                - input_file
                - date_format
                - date_column
                - band_names
            additionalProperties: False
        AGDCv2:  # TODO
            type: string
    pipeline:
        type: object
        description: Specify the tasks to run in a computational pipeline
        properties:
            overwrite:
                type: boolean
                default: True
            tasks:
                "$ref": "#/definitions/tasks"
        required:
            - tasks
    tasks:  # TODO
        type: object
        description: A list of task to compute
        properties:
            task:
                type: string
            require:
                "$ref": "#/definitions/task_spec"
            output:
                "$ref": "#/definitions/task_spec"
            config:
                type: object
    task_spec:
        type: object
        description: A specification that a task does or needs something
        properties:
            data:
                "$ref": "#/types/array_str"
            record:
                "$ref": "#/types/array_str"
            cache:
                "$ref": "#/types/array_str"
        minProperties: 1
        maxProperties: 3
        additionalProperties: False
types:
    array_num:
        type: array
        items:
            type: number
    array_str:
        type: array
        items:
            type: string
